language: cpp

compiler:
  - gcc

matrix:

  allow_failures:
    - os: osx
    - os: windows

  include:

    - os: linux
      env: REGISTER_WIDTH=auto

    - os: osx
      env: REGISTER_WIDTH=auto

    - os: windows
      env: REGISTER_WIDTH=auto

    - os: osx
      env: REGISTER_WIDTH=128

    - os: linux
      env: REGISTER_WIDTH=128

    - os: linux
      env: REGISTER_WIDTH=256
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install: 
        - sudo apt-get install -qq g++-6
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      # addons:
      #   apt:
      #     packages:
      #       - g++-6

script:
    - mkdir build 
    - cd build
    - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
    - make -j 2
