language: cpp

os:
    - linux
    - osx
    - windows

compiler: 
    - gcc

matrix:
    allow_failures:
        - os: osx
        - os: windows
    env:
    matrix:
          - TARGET="auto"
          - TARGET="128"
          - TARGET="256"       
          - TARGET="512"       

before_script:
    - mkdir build 
    - cd build
    - cmake .. -D REGISTER_WIDTH=$TARGET

script:
    make -j 2
