language: cpp

compiler:
  - gcc

matrix:

  fast_finish: true

  allow_failures:
    - os: windows

  include:

    - name: linux X 128
      os: linux
      env: SIMD_WIDTH=128
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DSIMD_WIDTH=$SIMD_WIDTH
        - make -j 2
        - ./bin/test_bin
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get remove -y cmake
        - mkdir -p $HOME/usr
        - export PATH="$HOME/usr/bin:$PATH"
        - wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh
        - chmod +x cmake-3.10.0-Linux-x86_64.sh
        - ./cmake-3.10.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
      install: 
        - sudo apt-get install -qq g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

    - name: osx X 128
      os: osx
      env: SIMD_WIDTH=128
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DSIMD_WIDTH=$SIMD_WIDTH
        - make -j 2
        - ./bin/test_bin

    - name: windows X 128
      os: windows
      env: SIMD_WIDTH=128
      install: 
        - choco install make windows-sdk-8.1 python -y
        - choco install cmake.install --version 3.10.0 --allow-downgrade --installargs 'ADD_CMAKE_TO_PATH=System' -y
        - choco upgrade mingw make -y
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DSIMD_WIDTH=$SIMD_WIDTH -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DPYTHON_INCLUDE_DIR=C:/Python37/include -DPYTHON_LIBRARY=C:/Python37/libs -G "Unix Makefiles"
        - make
        - ./bin/test_bin

    - name: linux X 256
      os: linux
      env: SIMD_WIDTH=256
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get remove -y cmake
        - mkdir -p $HOME/usr
        - export PATH="$HOME/usr/bin:$PATH"
        - wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh
        - chmod +x cmake-3.10.0-Linux-x86_64.sh
        - ./cmake-3.10.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
      install: 
        - sudo apt-get install -qq g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
        - sudo apt-get remove -y cmake
        - mkdir -p $HOME/usr
        - export PATH="$HOME/usr/bin:$PATH"
        - wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh
        - chmod +x cmake-3.10.0-Linux-x86_64.sh
        - ./cmake-3.10.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DSIMD_WIDTH=$SIMD_WIDTH
        - make -j 2
        - ./bin/test_bin

    - name: osx X 256
      os: osx
      env: SIMD_WIDTH=256
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DSIMD_WIDTH=$SIMD_WIDTH
        - make -j 2
        - ./bin/test_bin

    - name: windows X 256
      os: windows
      env: SIMD_WIDTH=256

    - name: linux X 512
      os: linux
      env: SIMD_WIDTH=512
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get remove -y cmake
        - mkdir -p $HOME/usr
        - export PATH="$HOME/usr/bin:$PATH"
        - wget https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh
        - chmod +x cmake-3.10.0-Linux-x86_64.sh
        - ./cmake-3.10.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
      install: 
        - sudo apt-get install -qq g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

    - name: osx X 512
      os: osx
      env: SIMD_WIDTH=512
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DSIMD_WIDTH=$SIMD_WIDTH
        - make -j 2

    - name: windows X 512
      os: windows
      env: SIMD_WIDTH=512

script: 
  - mkdir build 
  - cd build
  - cmake .. -DSIMD_WIDTH=$SIMD_WIDTH
  - make -j 2
