# vim:ft=ansible:
language: cpp

compiler:
  - gcc

dist: trusty

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
    - env: REGISTER_WIDTH=auto
    - env: REGISTER_WIDTH=128
    - env: REGISTER_WIDTH=256
      
script:
    - mkdir build 
    - cd build
    - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
    - make -j 2
