language: cpp

compiler:
  - gcc

matrix:

  fast_finish: true

  allow_failures:
    - os: osx
    - os: windows

  include:

    - os: linux
      env: REGISTER_WIDTH=128
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install: 
        - sudo apt-get install -qq g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

    - os: osx
      env: REGISTER_WIDTH=128
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: windows
      env: REGISTER_WIDTH=128
      install: choco install make python anaconda3
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH -DPYTHON_INCLUDE_DIR=C:/Python37/include -DPYTHON_LIBRARY=C:/Python37/libs -G "Unix Makefiles"
        - make
        - ./bin/test_bin

    - os: linux
      env: REGISTER_WIDTH=256
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install: 
        - sudo apt-get install -qq g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: osx
      env: REGISTER_WIDTH=256
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: windows
      env: REGISTER_WIDTH=256

    - os: linux
      env: REGISTER_WIDTH=512
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install: 
        - sudo apt-get install -qq g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

    - os: osx
      env: REGISTER_WIDTH=512
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2

    - os: windows
      env: REGISTER_WIDTH=512

script: 
  - mkdir build 
  - cd build
  - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
  - make -j 2
