language: cpp

os:
    - linux
    - osx
    - windows

allow_failures:
    - os: osx
    - os: windows

compiler: 
    - gcc

env:
    matrix:
        - TARGET="auto"
        - TARGET="128"
        - TARGET="256"       
        - TARGET="512"       

script:
    - mkdir build 
    - cd build_
    - cmake .. -D REGISTER_WIDTH=$TARGET
    - make -j 2
