language: cpp

compiler:
  - gcc

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env: REGISTER_WIDTH=auto

    - os: osx
      env: REGISTER_WIDTH=auto

    - os: osx
      env: REGISTER_WIDTH=128

    - os: linux
      env: REGISTER_WIDTH=128

    - os: linux
      env: REGISTER_WIDTH=256
      sudo: yes
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - g++-4.8

script:
    - mkdir build 
    - cd build
    - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
    - make -j 2
