language: cpp

compiler:
  - gcc

sudo: yes
dist: trusty
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install: 
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

matrix:

  fast_finish: true

  allow_failures:
    - os: osx
    - os: windows

  include:

    - os: linux
      env: REGISTER_WIDTH=auto
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: osx
      env: REGISTER_WIDTH=auto
      before_install:
        - brew install gcc && CC=gcc-6 && CXX=g++-6
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: windows
      env: REGISTER_WIDTH=auto
      install: choco install make
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DPYTHON_INCLUDE_DIR=C:\Python27\include -DPYTHON_LIBRARY=C:\Python27\libs 
        - make
        - ./bin/test_bin

    - os: linux
      env: REGISTER_WIDTH=128
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: osx
      env: REGISTER_WIDTH=128
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: windows
      env: REGISTER_WIDTH=128
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: linux
      env: REGISTER_WIDTH=256
      sudo: yes
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install: 
        - sudo apt-get install -qq g++-6
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      script: 
        - mkdir build 
        - cd build
        - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
        - make -j 2
        - ./bin/test_bin

    - os: linux
      env: REGISTER_WIDTH=256

    - os: osx
      env: REGISTER_WIDTH=256

    - os: windows
      env: REGISTER_WIDTH=256

    - os: linux
      env: REGISTER_WIDTH=512

    - os: osx
      env: REGISTER_WIDTH=512

    - os: windows
      env: REGISTER_WIDTH=512

script: 
  - mkdir build 
  - cd build
  - cmake .. -DREGISTER_WIDTH=$REGISTER_WIDTH
  - make -j 2
